name: Publish library  

on:
  push:
     tags:        
      - "**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Add NuGet source
      run: dotnet nuget add source https://nuget.pkg.github.com/The-Chest/index.json --name github --username The-Chest --password "${{ secrets.NUGET_APIKEY }}" --store-password-in-clear-text 
    - name: Write release version
      run: |
        VERSION=${GITHUB_REF_NAME#v}
        echo Version: $VERSION
        echo "VERSION=$VERSION" >> $GITHUB_ENV
    - name: Restore dependencies
      run: dotnet restore src/TheChest.Inventories
    - name: Build project
      run: dotnet build src/TheChest.Inventories --no-restore --configuration Release
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: ${{ github.ref_name }}
        path: 'src/TheChest.Inventories/bin/Release'
        retention-days: 14
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x
      - name: Write release version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo Version: $VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.2.1
        with:
          name: ${{ github.ref_name }}
          path: 'src/TheChest.Inventories/bin/Release'
      - name: Add NuGet source
        run: dotnet nuget add source https://nuget.pkg.github.com/The-Chest/index.json --name github --username The-Chest --password "${{ secrets.NUGET_APIKEY }}" --store-password-in-clear-text 
      - name: Restore dependencies
        run: dotnet restore src/TheChest.Inventories
      - name: Pack library
        run: dotnet pack src/TheChest.Inventories --configuration Release /p:Version=${VERSION} --no-build --output .
      - name: Push library to Github Packages
        run: dotnet nuget push TheChest.Inventories.${VERSION}.nupkg --source https://nuget.pkg.github.com/The-Chest/index.json --api-key "${{secrets.GH_NUGET_APIKEY}}"
      - name: Push library to Nuget
        run: dotnet nuget push TheChest.Inventories.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key "${{secrets.NUGET_APIKEY}}"
      - name: Upload release attachment
        uses: actions/github-script@v4
        with:
          script: |
            const fs = require('fs');
            const tag = context.ref.replace("refs/tags/", "");
            const release = await github.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag
            });
            const version = tag.replace("v", "");
            const fileName = `TheChest.Inventories.${version}.nupkg`;
            await github.repos.uploadReleaseAsset({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: release.data.id,
              name: fileName,
              data: await fs.readFileSync(`./${fileName}`)
            });
