name: Publish library  

on:
  push:
     tags:        
      - "**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Write release version
      run: |
        VERSION=${GITHUB_REF_NAME#v}
        echo Version: $VERSION
        echo "VERSION=$VERSION" >> $GITHUB_ENV
    - name: Restore dependencies
      run: dotnet restore src/TheChest.Inventories
    - name: Build project
      run: dotnet build src/TheChest.Inventories --no-restore --configuration Release
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: ${{ github.ref_name }}
        path: 'src/TheChest.Inventories/bin/Release'
        retention-days: 14
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x
      - name: Write release version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo Version: $VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.2.1
        with:
          name: ${{ github.ref_name }}
          path: 'src/TheChest.Inventories/bin/Release'
      - name: Restore dependencies
        run: dotnet restore src/TheChest.Inventories
      - name: Pack library
        run: dotnet pack src/TheChest.Inventories --configuration Release /p:Version=${VERSION} --no-build --output .
      - name: Push library
        run: dotnet nuget push TheChest.Inventories.${VERSION}.nupkg --source https://nuget.pkg.github.com/The-Chest/index.json --api-key "${{secrets.NUGET_APIKEY}}"
