name: Publish Source Files Manually

on:
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:

permissions:
  contents: read

env:
  PROJECT_NAME: "TheChest.Inventories"
  SOURCE_DIR: "src"
  RELEASE_OUTPUT_DIR: "src/bin/Release/netstandard2.1"

jobs:
  list-tags:
    name: "List Tags"
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.get-tags.outputs.tags }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Get all tags
        id: get-tags
        run: |
          TAGS=$(git tag --list | jq -R -s -c 'split("\n")[:-1] | map(ltrimstr("v"))')
          echo "tags=$TAGS" >> "$GITHUB_OUTPUT"

  publish-src-files:
    name: "Publish Source Files"
    needs: list-tags
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        version: ${{ fromJson(needs.list-tags.outputs.tags) }}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ matrix.version }}

      - name: Zip Folder
        run: zip -r "${{ env.PROJECT_NAME }}.${{ matrix.version }}.zip" src/ -i "*.cs"

      - name: Upload Source Files to release
        uses: The-Chest/Actions/upload-release-artifacts@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          path: "src"
          name: "${{ env.PROJECT_NAME }}.${{ matrix.version }}.zip"
          version: "${{ matrix.version }}"